// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCJsRTdU2teYbXgzLrKxjJgK6oSVh3I6A',
    appId: '1:577463655266:web:56dbc8081eab9867272a3b',
    messagingSenderId: '577463655266',
    projectId: 'hckim-flutter-web-portfolio',
    authDomain: 'hckim-flutter-web-portfolio.firebaseapp.com',
    storageBucket: 'hckim-flutter-web-portfolio.appspot.com',
    measurementId: 'G-7SMWV75YZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74C7DlYIH60wLvcLiOtllpAK4VudHcCs',
    appId: '1:577463655266:android:9fdd63b6651d0104272a3b',
    messagingSenderId: '577463655266',
    projectId: 'hckim-flutter-web-portfolio',
    storageBucket: 'hckim-flutter-web-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcXvzIErJKZUtB-RK3VtrVXjgL2qf9yJU',
    appId: '1:577463655266:ios:78146a6289325bb5272a3b',
    messagingSenderId: '577463655266',
    projectId: 'hckim-flutter-web-portfolio',
    storageBucket: 'hckim-flutter-web-portfolio.appspot.com',
    iosBundleId: 'com.example.flutterWebPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcXvzIErJKZUtB-RK3VtrVXjgL2qf9yJU',
    appId: '1:577463655266:ios:52b083e8a95b7b83272a3b',
    messagingSenderId: '577463655266',
    projectId: 'hckim-flutter-web-portfolio',
    storageBucket: 'hckim-flutter-web-portfolio.appspot.com',
    iosBundleId: 'com.example.flutterWebPortfolio.RunnerTests',
  );
}
